# Generated by Django 5.0.7 on 2024-07-14 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='create_time',
            field=models.IntegerField(default=1720917821.2653923),
        ),
    ]
