# Generated by Django 5.0.7 on 2024-07-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0003_roles_alter_users_create_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('parentId', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('categoryId', models.CharField(max_length=15)),
                ('PategoryId', models.CharField(max_length=15)),
                ('price', models.IntegerField()),
                ('desc', models.CharField(max_length=1000)),
                ('status', models.IntegerField(default=1)),
                ('images', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='create_time',
            field=models.IntegerField(default=1720940593.0480661),
        ),
    ]
