# Generated by Django 5.0.7 on 2024-07-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0004_categories_products_alter_users_create_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='PategoryId',
            new_name='PcategoryId',
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='users',
            name='create_time',
            field=models.IntegerField(default=1721374293.4212224),
        ),
    ]
