# Generated by Django 5.0.7 on 2024-07-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0005_rename_pategoryid_products_pcategoryid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='PcategoryId',
            new_name='PCategoryId',
        ),
        migrations.AlterField(
            model_name='users',
            name='create_time',
            field=models.IntegerField(default=1721374394.3708203),
        ),
    ]
