# Generated by Django 5.0.7 on 2024-07-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api', '0013_alter_roles_authname_alter_users_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='menus',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='create_time',
            field=models.IntegerField(default=1721551899.3980882),
        ),
    ]
